name: Release Statically Linked Rust Binary

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl       # Linux (musl)
          - aarch64-unknown-linux-musl      # ARM Linux (musl)

    env:
      BINARY_NAME: Nurse_Assistant

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Cross
        run: cargo install cross

      - name: Verify Cross Installation
        run: cross --version

      - name: Build with Cross
        run: cross build --target ${{ matrix.target }} --release --verbose

      - name: Debug - List Compiled Files
        run: ls -lah target/${{ matrix.target }}/release/

      - name: Create Release Archive
        run: |
          mkdir -p release
          BINARY_PATH="target/${{ matrix.target }}/release/nurse_assistant"

          if [ ! -f "$BINARY_PATH" ]; then
            echo "Error: Binary not found at $BINARY_PATH"
            exit 1
          fi

          cp "$BINARY_PATH" release/

          if [[ "${{ matrix.target }}" == *"windows"* ]]; then
            zip -r "release/${{ matrix.target }}.zip" release
          else
            tar -czvf "release/${{ matrix.target }}.tar.gz" -C release nurse_assistant
          fi

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.NA }}
